### ISSUE TITLE
🐞 -  duplicateAnchorHandling set to 'registerFirst' but errors are still being thrown.

### ISSUE THREAD

**Issue by selected-pixel-jameson** [hakimio/ngx-ui-tour#125]
### Which ngx-ui-tour-* package is the source of the bug?

ionic

### Description

Setup a tour with the following steps and anchors.

```
steps: [
			{
				anchorId: 'tour.issue.view-details',
				content: '<p>You can view more information about this issue by clicking here.</p>',
				title: 'View Details',
				duplicateAnchorHandling: 'registerFirst',
				delayBeforeStepShow: 1500,
			},
			{
				anchorId: 'tour.issue.owned',
				content: '<p>Key Collector allows you to manage your comic book collection. You can click here to add issues you own to your collection.</p>',
				duplicateAnchorHandling: 'registerFirst',
				title: 'Add Owned Issue',
			},
			{
				anchorId: 'tour.issue.wanted',
				content: '<p>You can click here to add items to your wishlist.</p>',
				duplicateAnchorHandling: 'registerFirst',
				title: 'Wishlist',
			},
			{
				anchorId: 'tour.issue.ebay',
				content: '<p>You can use the eBay button to be taken to listings of this issue on eBay.</p></br><p>Note: Key Collector receives a small comission when you purchase items on eBay through this link.</p>',
				duplicateAnchorHandling: 'registerFirst',
				title: 'Purchase on eBay',
			}],
```

I'm receiving this error.

```
mplate.html:14 ERROR Error: Tour anchor with id "tour.issue.ebay" already registered!
    at IonTourService.register (ngx-ui-tour-core.mjs:593:27)
    at TourAnchorIonPopoverDirective.ngOnInit (ngx-ui-tour-ionic.mjs:93:26)
    at callHook (core.mjs:2434:22)
    at callHooks (core.mjs:2403:17)
    at executeInitAndCheckHooks (core.mjs:2354:9)
    at selectIndexInternal (core.mjs:9059:17)
    at ɵɵadvance (core.mjs:9042:5)
    at IssueDetailItemComponent_Template (template.html:146:34)
    at executeTemplate (core.mjs:10441:9)
    at refreshView (core.mjs:10326:13)
h
```

### Angular version

15.0.4

### Ngx UI Tour version

1.7.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by hakimio** [comment]
I would guess the issue here is that your `tourService.initialize()` call happens after anchor registration. Where are you calling `tourService.initialize()`?
Also, you don't have to repeat the same configs, you can just [set the defaults](https://hakimio.github.io/ngx-ui-tour/ion-popover/Misc#defauls).

**Comment by selected-pixel-jameson** [comment]
@hakimio I'm registering the steps when I call init. `this.tourService.initialize(searchTourItem.steps, searchTourItem.settings);`

**Comment by hakimio** [comment]
I mean are you calling `initialize()` in component constructor, `ngOnInit` or sometime even later on user interaction or when some data is loaded.
Would be great if you could provide a reproduction of your issue: https://stackblitz.com/edit/angular-wau2z8?file=src%2Fapp%2Fui-tour-demo.component.ts

**Comment by selected-pixel-jameson** [comment]
@hakimio It's not a simple implementation. This is a tabbed Ionic application using multiple nested ion-routers. 
My goal was to create a Service / Store to maintain all of the logic that I'm implementing to maintain if a user has viewed a specific tour.

This is the Angular class that I'm implementing and then adding it as a service for the individual pages / classes that need it.
```
import { Injectable } from "@angular/core";
import { NavigationEnd, NavigationStart, Router, RouterEvent } from "@angular/router";
import { Preferences } from "@capacitor/preferences";
import { TourService, } from "ngx-ui-tour-ionic";
import { IonStepOption } from "ngx-ui-tour-ionic/lib/step-option.interface";

import { filter, take } from "rxjs";


export interface IClickedItems {
	filterV1: boolean
}

interface ITourItem {
	key: string,
	version: string;
	steps: Array<IonStepOption>
	settings: IonStepOption
}

export enum TourStep {
	search = 'tour.search',
	issue = 'tour.issue',
	bulkAdd = 'tour.bulk.add'
}


@Injectable({
	providedIn: "root",
})
export class TourStore {

	forceEnd: boolean = false
	navigating: boolean = false

	searchTourItem: ITourItem = {
		key: 'tour.search',
		version: '1',
		steps: [{
			anchorId: 'tour.search.searchbar.Series',
			content: '<p>When searching by series you can search for a series or a series and issue #.</p><br/><p>For example:<br/> Amazing Spider-Man #500</p>',
			title: 'Searching Series',
			isAsync: true,
			delayBeforeStepShow: 500
		},
		{
			anchorId: 'tour.search.searchtypes',
			content: '<p>There are various different ways to search the Key Collector database.</p><br/><p>Hint: If you are looking for a specific issue you should search by issue.</p>',
			title: 'Search Types'
		},
		{
			anchorId: 'tour.search.nonKeys',
			content: '<p>Turning on the non-keys filter will show all issues in the key collector database, not just the key issues.</p>',
			title: 'Non-Key Toggling',
		}],
		settings: {
			duplicateAnchorHandling: 'registerFirst',
			showArrow: true,
			disablePageScrolling: true,
			enableBackdrop: false,
			smoothScroll: true,
			placement: { alignment: "center" },
		}

	}
	issueTourItem: ITourItem = {
		key: 'tour.issue',
		version: '1',
		steps: [
			{
				anchorId: 'tour.issue.view-details',
				content: '<p>You can view more information about this issue by clicking here.</p>',
				title: 'View Details',
				isAsync: true,
				delayBeforeStepShow: 500
			},
			{
				anchorId: 'tour.issue.owned',
				content: '<p>Key Collector allows you to manage your comic book collection. You can click here to add issues you own to your collection.</p>',
				title: 'Add Owned Issue',
			},
			{
				anchorId: 'tour.issue.wanted',
				content: '<p>You can click here to add items to your wishlist.</p>',
				title: 'Wishlist',
			},
			{
				anchorId: 'tour.issue.ebay',
				content: '<p>You can use the eBay button to be taken to listings of this issue on eBay.</p></br><p>Note: Key Collector receives a small comission when you purchase items on eBay through this link.</p>',
				title: 'Purchase on eBay',
			}],
		settings: {
			duplicateAnchorHandling: 'registerFirst',
			showArrow: true,
			disablePageScrolling: true,
			enableBackdrop: true,
			smoothScroll: true,
			placement: { alignment: "center" },
		}
	}


	bulkAddTourItem: ITourItem = {
		key: 'tour.bulk.add',
		version: '1',
		steps: [
			{
				anchorId: 'tour.issue.bulk-add',
				content: '<p>You can add items from this series in bulk by clicking here.</p>',
				title: 'Bulk Add'
			},
		],
		settings: {
			showArrow: true,
			disablePageScrolling: true,
			enableBackdrop: true,
			smoothScroll: true,
			placement: { alignment: "center" },
		}
	}

	tourItems: Array<ITourItem> = [this.searchTourItem, this.issueTourItem, this.bulkAddTourItem]

	constructor(private tourService: TourService, private router: Router) {
		this.router.events.pipe(filter(event => event instanceof NavigationStart || event instanceof NavigationEnd)).subscribe((event: RouterEvent) => {

			if (event instanceof NavigationEnd) {
				console.log("Navigation End ", this.navigating)
				this.navigating = false
			} else {
				console.log("Navigation Start ", this.navigating)
				this.stopTour()
				this.navigating = true
			}
		})
	}

	async startTour(key: string, callback: Function = null) {
		console.log("Navigating: ", this.navigating)
		let searchTourItem = this.tourItems.find(t => t.key === key)
		let version = await Preferences.get({ key: key })
		this.forceEnd = false
		if (!this.navigating) {
			if (!version.value || version.value !== searchTourItem.version) {
				this.tourService.initialize(searchTourItem.steps, searchTourItem.settings);
				this.tourService
					.end$
					.pipe(take(1))
					.subscribe(async () => {
						if (!this.forceEnd) {
							//await this.markTourComplete(key)
							if (callback) {
								callback('complete')
							}
						}
						this.forceEnd = false
					});
				this.tourService.start()
			} else if (callback && !this.forceEnd) {
				callback('complete')
			}
		}
	}

	stopTour() {
		this.forceEnd = true
		this.tourService.end()
	}

	async markTourComplete(key: string) {
		let searchTourItem = this.tourItems.find(t => t.key === key)
		await Preferences.set({ key: key, value: searchTourItem.version });
	}



}

```

**Comment by hakimio** [comment]
Make sure your `setDefaults()` is called before anchor registration:
```ts
this.tourService.setDefaults({
    duplicateAnchorHandling: 'registerFirst'
});
```

Right now it doesn't seem to be the case.

**Comment by selected-pixel-jameson** [comment]
That solved it. Thank you!
